# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1426, 878)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 650, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 690, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 80, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.id = QtWidgets.QLineEdit(self.centralwidget)
        self.id.setGeometry(QtCore.QRect(120, 640, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.id.setFont(font)
        self.id.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.id.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.id.setClearButtonEnabled(False)
        self.id.setObjectName("id")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(120, 690, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.dept = QtWidgets.QLineEdit(self.centralwidget)
        self.dept.setGeometry(QtCore.QRect(260, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dept.setFont(font)
        self.dept.setObjectName("dept")
        self.company = QtWidgets.QLineEdit(self.centralwidget)
        self.company.setGeometry(QtCore.QRect(160, 130, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.company.setFont(font)
        self.company.setObjectName("company")
        self.label_qr_code = QtWidgets.QLabel(self.centralwidget)
        self.label_qr_code.setGeometry(QtCore.QRect(430, 100, 250, 250))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_qr_code.setFont(font)
        self.label_qr_code.setStyleSheet("background-color: rgb(243, 228, 255);")
        self.label_qr_code.setText("")
        self.label_qr_code.setObjectName("label_qr_code")
        self.make_qr = QtWidgets.QPushButton(self.centralwidget)
        self.make_qr.setGeometry(QtCore.QRect(40, 390, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.make_qr.setFont(font)
        self.make_qr.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 138, 138, 1), stop:1 rgba(46, 138, 138, 1));\n"
"    color: #ffffff;\n"
"    Text-align: center;\n"
"    font: 75 12pt \"Samsung Sharp Sans\";\n"
"    border-radius: 5px;\n"
"} \n"
"\n"
"QPushButton:disabled{\n"
"    background-color:#7B7B7B;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #4DD0E1;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:#218CB3;\n"
"}\n"
"\n"
"QPushButton:flat{\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:default{ \n"
"    border-color: navy;\n"
"}")
        self.make_qr.setDefault(False)
        self.make_qr.setObjectName("make_qr")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(710, 50, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(880, 50, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(710, 90, 103, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.label_time.setText("")
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.label_date = QtWidgets.QLabel(self.centralwidget)
        self.label_date.setGeometry(QtCore.QRect(880, 90, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_date.setFont(font)
        self.label_date.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.label_date.setText("")
        self.label_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date.setObjectName("label_date")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 180, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.print_qr = QtWidgets.QPushButton(self.centralwidget)
        self.print_qr.setGeometry(QtCore.QRect(160, 390, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.print_qr.setFont(font)
        self.print_qr.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 138, 138, 1), stop:1 rgba(46, 138, 138, 1));\n"
"    color: #ffffff;\n"
"    Text-align: center;\n"
"    font: 75 12pt \"Samsung Sharp Sans\";\n"
"    border-radius: 5px;\n"
"} \n"
"\n"
"QPushButton:disabled{\n"
"    background-color:#7B7B7B;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #4DD0E1;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:#218CB3;\n"
"}\n"
"\n"
"QPushButton:flat{\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:default{ \n"
"    border-color: navy;\n"
"}")
        self.print_qr.setObjectName("print_qr")
        self.comboBox_com_ports = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_com_ports.setGeometry(QtCore.QRect(250, 230, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox_com_ports.setFont(font)
        self.comboBox_com_ports.setObjectName("comboBox_com_ports")
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_button.setGeometry(QtCore.QRect(40, 230, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.connect_button.setFont(font)
        self.connect_button.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 138, 138, 1), stop:1 rgba(46, 138, 138, 1));\n"
"    color: #ffffff;\n"
"    Text-align: center;\n"
"    font: 75 12pt \"Samsung Sharp Sans\";\n"
"    border-radius: 5px;\n"
"} \n"
"\n"
"QPushButton:disabled{\n"
"    background-color:#7B7B7B;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #4DD0E1;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:#218CB3;\n"
"}\n"
"\n"
"QPushButton:flat{\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:default{ \n"
"    border-color: navy;\n"
"}")
        self.connect_button.setAutoDefault(False)
        self.connect_button.setDefault(False)
        self.connect_button.setFlat(False)
        self.connect_button.setObjectName("connect_button")
        self.display = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.display.setGeometry(QtCore.QRect(420, 390, 451, 201))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.display.setFont(font)
        self.display.setObjectName("display")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(190, 180, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.status = QtWidgets.QLineEdit(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(40, 290, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.status.setFont(font)
        self.status.setInputMask("")
        self.status.setText("")
        self.status.setObjectName("status")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(710, 250, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.value = QtWidgets.QLabel(self.centralwidget)
        self.value.setGeometry(QtCore.QRect(880, 280, 401, 211))
        font = QtGui.QFont()
        font.setPointSize(120)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.value.setFont(font)
        self.value.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.value.setAlignment(QtCore.Qt.AlignCenter)
        self.value.setObjectName("value")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(710, 140, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.ng_count = QtWidgets.QLabel(self.centralwidget)
        self.ng_count.setGeometry(QtCore.QRect(710, 200, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ng_count.setFont(font)
        self.ng_count.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ng_count.setText("")
        self.ng_count.setAlignment(QtCore.Qt.AlignCenter)
        self.ng_count.setObjectName("ng_count")
        self.ok_count = QtWidgets.QLabel(self.centralwidget)
        self.ok_count.setGeometry(QtCore.QRect(820, 200, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ok_count.setFont(font)
        self.ok_count.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.ok_count.setText("")
        self.ok_count.setAlignment(QtCore.Qt.AlignCenter)
        self.ok_count.setObjectName("ok_count")
        self.total_count = QtWidgets.QLabel(self.centralwidget)
        self.total_count.setGeometry(QtCore.QRect(930, 200, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.total_count.setFont(font)
        self.total_count.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.total_count.setText("")
        self.total_count.setAlignment(QtCore.Qt.AlignCenter)
        self.total_count.setObjectName("total_count")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(720, 170, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(820, 170, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(930, 170, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.save_data = QtWidgets.QPushButton(self.centralwidget)
        self.save_data.setGeometry(QtCore.QRect(120, 740, 100, 41))
        font = QtGui.QFont()
        font.setFamily("Samsung Sharp Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.save_data.setFont(font)
        self.save_data.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 138, 138, 1), stop:1 rgba(46, 138, 138, 1));\n"
"    color: #ffffff;\n"
"    Text-align: center;\n"
"    font: 75 12pt \"Samsung Sharp Sans\";\n"
"    border-radius: 5px;\n"
"} \n"
"\n"
"QPushButton:disabled{\n"
"    background-color:#7B7B7B;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #4DD0E1;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:#218CB3;\n"
"}\n"
"\n"
"QPushButton:flat{\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:default{ \n"
"    border-color: navy;\n"
"}")
        self.save_data.setObjectName("save_data")
        self.value_adc = QtWidgets.QLabel(self.centralwidget)
        self.value_adc.setGeometry(QtCore.QRect(300, 500, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.value_adc.setFont(font)
        self.value_adc.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.value_adc.setText("")
        self.value_adc.setAlignment(QtCore.Qt.AlignCenter)
        self.value_adc.setObjectName("value_adc")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(380, 360, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(300, 460, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(380, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(240, 10, 771, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 610, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.data_table = QtWidgets.QTableWidget(self.centralwidget)
        self.data_table.setGeometry(QtCore.QRect(440, 650, 501, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.data_table.setFont(font)
        self.data_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.data_table.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.data_table.setObjectName("data_table")
        self.data_table.setColumnCount(4)
        self.data_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.data_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.data_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.data_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.data_table.setHorizontalHeaderItem(3, item)
        self.ngay = QtWidgets.QLabel(self.centralwidget)
        self.ngay.setGeometry(QtCore.QRect(210, 340, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ngay.setFont(font)
        self.ngay.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.ngay.setText("")
        self.ngay.setAlignment(QtCore.Qt.AlignCenter)
        self.ngay.setObjectName("ngay")
        self.thang = QtWidgets.QLabel(self.centralwidget)
        self.thang.setGeometry(QtCore.QRect(140, 340, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.thang.setFont(font)
        self.thang.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.thang.setText("")
        self.thang.setAlignment(QtCore.Qt.AlignCenter)
        self.thang.setObjectName("thang")
        self.nam = QtWidgets.QLabel(self.centralwidget)
        self.nam.setGeometry(QtCore.QRect(70, 340, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.nam.setFont(font)
        self.nam.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.nam.setText("")
        self.nam.setAlignment(QtCore.Qt.AlignCenter)
        self.nam.setObjectName("nam")
        self.enable_print = QtWidgets.QRadioButton(self.centralwidget)
        self.enable_print.setGeometry(QtCore.QRect(270, 395, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.enable_print.setFont(font)
        self.enable_print.setStyleSheet("QRadioButton {\n"
"    color: white;            /* Màu chữ */\n"
"\n"
"    border-radius: 5px;\n"
"    padding: 4px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color: red; /* Màu khi nút được chọn */\n"
"    border: 2px solid black;\n"
"}\n"
"")
        self.enable_print.setText("")
        self.enable_print.setObjectName("enable_print")
        self.qr_print = QtWidgets.QLineEdit(self.centralwidget)
        self.qr_print.setGeometry(QtCore.QRect(30, 505, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.qr_print.setFont(font)
        self.qr_print.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.qr_print.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.qr_print.setAlignment(QtCore.Qt.AlignCenter)
        self.qr_print.setClearButtonEnabled(False)
        self.qr_print.setObjectName("qr_print")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(30, 470, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(1250, 510, 61, 61))
        self.label_20.setStyleSheet("border-radius: 30px;\n"
"background-color: rgb(0, 0, 255);\n"
"")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(1140, 660, 41, 41))
        self.label_26.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(0, 0, 255);")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(1250, 750, 61, 61))
        self.label_21.setStyleSheet("border-radius: 30px;\n"
"background-color: rgb(0, 0, 255);\n"
"")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(980, 760, 61, 61))
        self.label_22.setStyleSheet("border-radius: 30px;\n"
"background-color: rgb(0, 0, 255);\n"
"")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(970, 510, 61, 61))
        self.label_28.setStyleSheet("border-radius: 30px;\n"
"background-color: rgb(0, 0, 255);\n"
"")
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(1090, 660, 41, 41))
        self.label_29.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(0, 0, 255);")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(1150, 580, 61, 61))
        self.label_24.setStyleSheet("border-radius: 30px;\n"
"background-color: rgb(0, 255, 0);\n"
"")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(1110, 710, 61, 61))
        self.label_27.setStyleSheet("border-radius: 30px;\n"
"background-color: rgb(0, 255, 0);\n"
"")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(1060, 580, 61, 61))
        self.label_30.setStyleSheet("border-radius: 30px;\n"
"background-color: rgb(0, 255, 0);\n"
"")
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1426, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionVer = QtWidgets.QAction(MainWindow)
        self.actionVer.setObjectName("actionVer")
        self.actionManual = QtWidgets.QAction(MainWindow)
        self.actionManual.setObjectName("actionManual")
        self.actionInfor = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/about.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInfor.setIcon(icon)
        self.actionInfor.setObjectName("actionInfor")
        self.menuAbout.addAction(self.actionVer)
        self.menuAbout.addAction(self.actionManual)
        self.menuAbout.addAction(self.actionInfor)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "Part Name:"))
        self.label_4.setText(_translate("MainWindow", "Vendor Code:"))
        self.make_qr.setText(_translate("MainWindow", "Make QR "))
        self.label_5.setText(_translate("MainWindow", "Time:"))
        self.label_7.setText(_translate("MainWindow", "Date:"))
        self.label_8.setText(_translate("MainWindow", "Part Code:"))
        self.print_qr.setText(_translate("MainWindow", "Print QR"))
        self.connect_button.setText(_translate("MainWindow", "Connect-Disconnect"))
        self.comboBox.setItemText(0, _translate("MainWindow", "DJ9600255A"))
        self.comboBox.setItemText(1, _translate("MainWindow", "DJ9600255B"))
        self.comboBox.setItemText(2, _translate("MainWindow", "DJ9600255C"))
        self.comboBox.setItemText(3, _translate("MainWindow", "DJ9600255D"))
        self.comboBox.setItemText(4, _translate("MainWindow", "DJ9600255E"))
        self.comboBox.setItemText(5, _translate("MainWindow", "DJ9600231A"))
        self.comboBox.setItemText(6, _translate("MainWindow", "DJ9600231B"))
        self.comboBox.setItemText(7, _translate("MainWindow", "DJ9600231C"))
        self.comboBox.setItemText(8, _translate("MainWindow", "DJ9600231D"))
        self.comboBox.setItemText(9, _translate("MainWindow", "DJ9600231E"))
        self.comboBox.setItemText(10, _translate("MainWindow", "DJ9600231H"))
        self.comboBox.setItemText(11, _translate("MainWindow", "DJ9600252A"))
        self.status.setPlaceholderText(_translate("MainWindow", "Please connect first"))
        self.label_10.setText(_translate("MainWindow", "Result:"))
        self.value.setText(_translate("MainWindow", "OK"))
        self.label_11.setText(_translate("MainWindow", "Count"))
        self.label_12.setText(_translate("MainWindow", "NG"))
        self.label_13.setText(_translate("MainWindow", "OK"))
        self.label_14.setText(_translate("MainWindow", "Total"))
        self.save_data.setText(_translate("MainWindow", "Save Data"))
        self.label_15.setText(_translate("MainWindow", "Log."))
        self.label_16.setText(_translate("MainWindow", "Value Check:"))
        self.label_17.setText(_translate("MainWindow", "QR Code."))
        self.label_18.setText(_translate("MainWindow", "Function Tester_ASSY CHARGER BASE-VS70"))
        self.label_6.setText(_translate("MainWindow", "JINGGUANG_ Ver.01 SN-0000-9999"))
        item = self.data_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No."))
        item = self.data_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.data_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ADC Value"))
        item = self.data_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Result"))
        self.label_19.setText(_translate("MainWindow", "QR Label."))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionVer.setText(_translate("MainWindow", "Ver"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
        self.actionInfor.setText(_translate("MainWindow", "Infor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
